create table public.names_cartridges
(
    id             Serial primary key not null,
    name           VARCHAR
);

create unique index names_cartridges_id_uindex ON public.names_cartridges(id);

create table public.cartridges
(
    id             Serial primary key not null,
    type_cartridge int,
    text_qr        VARCHAR,
    status         VARCHAR,
    text_status    TEXT,
    CONSTRAINT  cartridges_type_cartridge_fk foreign key (type_cartridge) REFERENCES names_cartridges(id)
);

create unique index cartridges_id_uindex ON public.cartridges(id);

create table public.person
(
    id             int primary key  generated by default as identity,
    username varchar(100) not null,
    password varchar not null,
    role varchar(100) not null
);

insert into public.person (username, password, role) values ('kopfire', '$2a$10$2yip1jTrE8sGy9cNyHsUJul5nMROmO6I.MqaWYS4JSTqPMJ/kjWBe', 'ROLE_ADMIN')